import Head from 'next/head';
import Image from 'next/image';
import DataTable from '../components/Table';
import styles from '../styles/Home.module.css';

let datas = require('../data/Data.json');
const searchHandler = function () {
  let search = document.getElementById('search').value;
  let result = datas.filter(data => data.name.toLowerCase().includes(search.toLowerCase()));
  console.log(result);
  return result;
}

export default function Home() {
  // const nameSearch = useRef(null);
  // console.log(datas);
  return (
    <div className={styles.container}>
      <Head>
        <title>Rental App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="shortcut icon" href="/Mi-logo.svg" type="image/x-icon" />
      </Head>

      <main className={styles.main}>

        <DataTable />

        <input type="search" placeholder='search...' onChange={searchHandler} />
        <table>
          <thead>
            <tr>
              <th>Sl</th>
              <th>name</th>
              <th>code</th>
              <th>availability</th>
              <th>need to repaire</th>
              <th>Durability</th>
              <th>Mileage</th>
            </tr>
          </thead>
          {/* mapping of the profile data for rendering the user's profile */}
          <tbody>
            {datas.map((data, index) => (
              <tr key={index}>
                <td>{index + 1}</td>
                <td >{data.name}</td>
                <td>{data.code}</td>
                <td>{data.availability ? 'true' : 'false'}</td>
                <td>{data.needing_repair ? 'true' : 'false'}</td>
                <td>{data.durability}</td>
                <td>{data.mileage}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
